name: Create a new tgif day
on:
  schedule:
    - cron:  '*/5 * * * 4'
  workflow_dispatch:

jobs:
  new:
    name: Create a new tgif day
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: cp src/example.md src/`date +"%Y-%m-%d"`.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create a new tgif day
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KINGKONG }}

      - uses: someimportantcompany/github-actions-slack-message@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: "Completa el TGIF de hoy en: https://github.com/ThingsO2/tgif/blob/main/src/example.md"
          color: good
