name: Create a new tgif day
on:
  schedule:
    - cron:  '0 5 * * 5'
  workflow_dispatch:

jobs:
  new:
    name: Create a new tgif day
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: ./newtgif.sh

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: someimportantcompany/github-actions-slack-message@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: "Completa el TGIF de hoy en: https://github.com/ThingsO2/tgif/blob/main/src/example.md"
          color: good
